#!/usr/bin/env bash
# Facts the README and CHANGELOG state about a running stack:
#
# - the RCON password is random, regenerated by the server on every start, and
#   the panel never shows or logs it (fingerprint before and after a restart
#   of mc; grep of the panel's pages and all logs);
# - the panel runs as uid 1001 in group 1000, with no capability, on a
#   read-only root filesystem, and still shows the JVM's CPU and memory;
# - no response says which Python it runs on (Server: kPanel).
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
DOCKER=${DOCKER:-docker}
P=${PROJECT:-kprcon}
PORT=${PORT:-18383}
work=$(mktemp -d)
cat >"$work/test.yml" <<YML
services:
  mc:
    ports: !reset []
  kpanel:
    ports: !override
      - "127.0.0.1:$PORT:8080"
    environment:
      KPANEL_UPDATE_CHECK: "0"
YML
# EXTRA_OVERLAY: more compose files, colon-separated, added after the test's
# own (e.g. one that undoes a fix, to see the test fail).
extra=()
IFS=: read -r -a _xo <<<"${EXTRA_OVERLAY:-}"
for _f in ${_xo[@]+"${_xo[@]}"}; do [[ -n $_f ]] && extra+=(-f "$_f"); done
DC=("$DOCKER" compose -p "$P" -f "$root/docker-compose.yml" -f "$work/test.yml" ${extra[@]+"${extra[@]}"})
cleanup() { "${DC[@]}" down -v --remove-orphans >/dev/null 2>&1 || true; rm -rf "$work"; }
trap cleanup EXIT
fail=0
check() { if [[ $1 == 1 ]]; then echo "  PASS  $2"; else echo "  FAIL  $2"; fail=1; fi; }
started() { for _ in $(seq 120); do "${DC[@]}" exec -T mc rcon-cli list >/dev/null 2>&1 && return 0; sleep 3; done; return 1; }
pw() { "${DC[@]}" exec -T mc sh -c 'grep "^rcon.password=" /data/server.properties | cut -d= -f2-' | tr -d '\r'; }

"${DC[@]}" up -d --build >/dev/null 2>&1
started || { echo "FAIL: the server never started" >&2; exit 1; }
first=$(pw)
pages=""
for path in / /settings /players /logs; do
  pages+=$(curl -s -H "Host: localhost:$PORT" "http://127.0.0.1:$PORT$path" || true)
done
"${DC[@]}" restart mc >/dev/null 2>&1
started || { echo "FAIL: the server never came back" >&2; exit 1; }
second=$(pw)
fp() { printf %s "$1" | sha256sum | cut -c1-12; }
logs=$("${DC[@]}" logs --no-color 2>&1)
check "$([[ ${#first} -ge 12 ]] && echo 1 || echo 0)" "the server generated a password (${#first} chars, sha256 $(fp "$first"))"
check "$([[ $first != "$second" && ${#second} -ge 12 ]] && echo 1 || echo 0)" "a restart generated a new one (sha256 $(fp "$second"))"
check "$([[ $pages != *"$first"* && ${#pages} -gt 1000 ]] && echo 1 || echo 0)" "the panel's pages don't show it"
check "$([[ $logs != *"$first"* && $logs != *"$second"* ]] && echo 1 || echo 0)" "no log contains either"
ident=$("${DC[@]}" exec -T kpanel id | tr -d '\r')
caps=$("${DC[@]}" exec -T kpanel grep -E '^Cap(Eff|Prm|Bnd):' /proc/self/status | awk '{print $2}' | tr -d '\r' | tr '\n' ' ')
rofs=$("${DC[@]}" exec -T kpanel sh -c 'touch /app/x 2>&1 || true' | tr -d '\r')
home=$(curl -s -D - -o "$work/home.html" -H "Host: localhost:$PORT" "http://127.0.0.1:$PORT/" | tr -d '\r')
check "$([[ $ident == "uid=1001(admin) gid=1000(mc)"* ]] && echo 1 || echo 0)" "the panel: $ident"
check "$([[ $caps == "0000000000000000 0000000000000000 0000000000000000 " ]] && echo 1 || echo 0)" "the panel has no capability (Eff Prm Bnd: $caps)"
check "$([[ $rofs == *"Read-only file system"* ]] && echo 1 || echo 0)" "its root filesystem is read-only"
rss=$("${DC[@]}" exec -T kpanel python -c 'import procstats; print((procstats.memory()["rss"] or 0) // 2**20)' | tr -d '\r')
check "$(grep -q 'CPU</div><div class=v>[0-9]' "$work/home.html" && [[ ${rss:-0} -gt 100 ]] && echo 1 || echo 0)" "as uid 1001 it still reads the JVM's CPU (dashboard tile) and memory (${rss:-?} MiB RSS)"
check "$([[ $home == *$'\n'"Server: kPanel"$'\n'* ]] && echo 1 || echo 0)" "Server header: $(grep -i '^server:' <<<"$home")"
exit $fail
