"""Every server.properties key: how to edit it, validate it, and explain it.

The key list, env-var routing, types, defaults and most descriptions come from
properties_meta.json, generated by tools/gen_meta.py from the server's own
server.properties, itzg's property-definitions.json and the Minecraft Wiki.
This module adds what those sources lack: what each difficulty and game mode
actually means, which keys are secret or locked, and grouping for the UI.
"""

import json
import re
from dataclasses import dataclass
from pathlib import Path

META = json.loads((Path(__file__).parent / "properties_meta.json").read_text())

# Never displayed, never written: secrets don't belong in git.
HIDDEN = {"rcon.password", "management-server-secret", "management-server-tls-keystore-password"}

# Displayed, but only changeable by hand in the compose, deliberately.
LOCKED = {
    "online-mode": "Off lets anyone join as any username, including an op's.",
    "white-list": "Turning it off opens the server to everyone who finds it.",
    "enforce-whitelist": "Part of the access control; see white-list.",
    "enable-rcon": "The panel and the backup sidecar both depend on RCON.",
    "rcon.port": "The backup sidecar connects to this port.",
    "server-port": "Must match the compose's host port mapping and the DNS setup.",
    "level-name": "Points the server at a different (likely empty) world folder.",
}

# Hand-written explanations where the wiki gives only numbers.
OPTION_TEXT = {
    "difficulty": {
        "peaceful": "No hostile mobs. Hunger never drains health, and health regenerates.",
        "easy": "Hostile mobs deal less damage. Starving stops at 5 hearts.",
        "normal": "Standard damage. Starving stops at half a heart.",
        "hard": "Mobs hit harder, starving can kill, and zombies can break doors.",
    },
    "gamemode": {
        "survival": "Gather, craft, take damage, die.",
        "creative": "Unlimited blocks, flying, invulnerable.",
        "adventure": "Survival, but blocks can't be broken or placed without the right tools.",
        "spectator": "Fly through everything; can't interact.",
    },
    "op-permission-level": {
        "0": "No op powers at all.",
        "1": "Bypass spawn protection only.",
        "2": "Plus cheat commands and command blocks.",
        "3": "Plus player management: kick, ban, op.",
        "4": "Everything, including stop and save commands.",
    },
    "function-permission-level": {
        "1": "Bypass spawn protection only.",
        "2": "Cheat commands (the default).",
        "3": "Plus player-management commands.",
        "4": "Every command.",
    },
    "region-file-compression": {
        "deflate": "Default. Smallest files.",
        "lz4": "Faster to read and write, larger files.",
        "none": "No compression. Largest files; only for special setups.",
    },
}

# Defaults for keys the wiki doesn't document (gen_meta warns about them).
# Without a known default, an untouched value like debug=false looked like a
# hand edit and was offered for import.
DEFAULT_FIX = {
    "debug": "false",
    "management-server-allowed-origins": "",
}

# Enum-like string keys whose options must be one of the listed values.
STRICT_ENUMS = {"difficulty", "gamemode", "region-file-compression"}

WORLDGEN = {"level-seed", "level-type", "generator-settings", "generate-structures",
            "initial-enabled-packs", "initial-disabled-packs"}
WORLDGEN_NOTE = "Only affects newly generated chunks or a new world, not what's already built."

GROUPS = [
    ("Gameplay", ["difficulty", "gamemode", "force-gamemode", "hardcore", "allow-flight",
                  "spawn-protection", "max-players", "player-idle-timeout",
                  "pause-when-empty-seconds"]),
    ("Server list & chat", ["motd", "hide-online-players", "enable-status", "status-heartbeat-interval",
                            "chat-spam-threshold-seconds", "command-spam-threshold-seconds",
                            "enforce-secure-profile", "enable-code-of-conduct", "bug-report-link",
                            "text-filtering-config", "text-filtering-version", "log-ips"]),
    ("Performance", ["view-distance", "simulation-distance", "entity-broadcast-range-percentage",
                     "max-tick-time", "max-chained-neighbor-updates", "network-compression-threshold",
                     "sync-chunk-writes", "region-file-compression", "use-native-transport", "rate-limit"]),
    ("Permissions", ["op-permission-level", "function-permission-level",
                     "broadcast-console-to-ops", "broadcast-rcon-to-ops"]),
    ("World generation", sorted(WORLDGEN) + ["max-world-size"]),
    ("Resource pack", ["resource-pack", "resource-pack-id", "resource-pack-prompt",
                       "resource-pack-sha1", "require-resource-pack"]),
    ("Access & network", ["online-mode", "white-list", "enforce-whitelist", "prevent-proxy-connections",
                          "accepts-transfers", "server-ip", "server-port", "enable-rcon", "rcon.port",
                          "enable-query", "query.port", "level-name"]),
]
OTHER_GROUP = "Advanced"


@dataclass(frozen=True)
class Prop:
    key: str
    env: str | None      # dedicated itzg env var, or None -> CUSTOM_SERVER_PROPERTIES
    kind: str            # "bool" | "int" | "enum" | "text"
    default: str
    desc: str
    options: tuple       # ((value, explanation), ...) suggestions
    strict: bool         # options are the only valid values
    min: int | None
    max: int | None
    locked: str          # reason, or "" if editable
    note: str            # extra caveat shown in the UI


def _int_range(typ: str):
    """'integer (3-32)' -> (3, 32); 'integer (1-(2^16 - 2))' -> (1, 65534)."""
    m = re.search(r"\((-?\d+)\s*[-–]\s*(\d+|\(2\^(\d+)\s*-\s*(\d+)\))\)", typ)
    if not m:
        return None, None
    hi = int(m.group(2)) if m.group(3) is None else 2 ** int(m.group(3)) - int(m.group(4))
    return int(m.group(1)), hi


def _build():
    props = {}
    for key, m in META["properties"].items():
        if key in HIDDEN:
            continue
        typ = m["type"]
        if "bool" in typ:
            kind = "bool"
        elif "int" in typ:
            kind = "int"
        elif m["options"] or key in OPTION_TEXT:
            kind = "enum"
        else:
            kind = "text"
        lo, hi = _int_range(typ) if kind == "int" else (None, None)
        texts = OPTION_TEXT.get(key, {})
        if texts:
            options = tuple(texts.items())
        else:
            # Plain tokens only: the wiki also bolds things like "Note:".
            options = tuple((o["value"], o["desc"]) for o in m["options"]
                            if re.fullmatch(r"[\w:.\-]*[\w.\-]", o["value"])
                            and not (kind == "bool" and o["value"] in ("true", "false")))
        if kind == "int" and texts:
            kind = "enum"  # e.g. permission levels: a few meaningful numbers
        props[key] = Prop(
            key=key, env=m["env"], kind=kind, default=DEFAULT_FIX.get(key, m["default"]), desc=m["desc"],
            options=options, strict=key in STRICT_ENUMS or (kind == "enum" and bool(texts)),
            min=lo, max=hi, locked=LOCKED.get(key, ""),
            note=WORLDGEN_NOTE if key in WORLDGEN else "",
        )
    return props


PROPS = _build()


def grouped(keys):
    """[(group, [keys...]), ...] in display order; unknown keys go to Advanced."""
    seen, out = set(), []
    for name, members in GROUPS:
        ks = [k for k in members if k in keys]
        seen.update(ks)
        if ks:
            out.append((name, ks))
    rest = sorted(k for k in keys if k not in seen)
    if rest:
        out.append((OTHER_GROUP, rest))
    return out


def normalize(p: Prop, value):
    """Comparable form, so "TRUE" == "true" and "08" == "8"."""
    if value is None:
        return None
    v = str(value).strip()
    if p.kind in ("bool", "enum"):
        v = v.lower()
        if p.key == "level-type" and ":" not in v and v:
            v = "minecraft:" + v  # the namespace may be omitted
        return v
    if p.kind == "int":
        try:
            return str(int(v))
        except ValueError:
            return v
    return v


def validate(p: Prop, raw: str) -> str:
    """The value to write, or raise ValueError with a readable message."""
    if p.locked:
        raise ValueError(f"{p.key} is locked: {p.locked}")
    v = (raw or "").strip()
    if "$" in v:
        raise ValueError(f"{p.key}: the $ character is not allowed (compose would treat it as a variable)")
    if any(ord(c) < 32 for c in v):
        raise ValueError(f"{p.key}: no line breaks or control characters")
    if p.kind == "bool":
        if v.lower() not in ("true", "false"):
            raise ValueError(f"{p.key}: must be true or false")
        return v.lower()
    if p.kind == "int" or (p.kind == "enum" and p.options and all(o[0].lstrip("-").isdigit() for o in p.options)):
        try:
            n = int(v)
        except ValueError:
            raise ValueError(f"{p.key}: must be a whole number") from None
        if p.min is not None and n < p.min or p.max is not None and n > p.max:
            raise ValueError(f"{p.key}: must be between {p.min} and {p.max}")
        if p.strict and str(n) not in [o[0] for o in p.options]:
            raise ValueError(f"{p.key}: must be one of {', '.join(o[0] for o in p.options)}")
        return str(n)
    if p.strict and v.lower() not in [o[0] for o in p.options]:
        raise ValueError(f"{p.key}: must be one of {', '.join(o[0] for o in p.options)}")
    if p.kind == "enum" and p.strict:
        return v.lower()
    if len(v) > 1000:
        raise ValueError(f"{p.key}: too long")
    return v


def parse_properties(text: str) -> dict:
    """Parse a Java .properties file as Minecraft writes it.

    Minecraft uses java.util.Properties, which escapes ':' and '=' and may write
    non-ASCII characters as \\uXXXX. A plain split on '=' would show
    'minecraft\\:normal', or garbled umlauts in a MOTD.
    """
    out = {}
    for line in text.splitlines():
        kv = _split(line)
        if kv:
            out[kv[0]] = kv[1]
    return out


def _split(line):
    """(key, value) of one properties line, or None for a blank or comment line."""
    line = line.strip()
    if not line or line[0] in "#!":
        return None
    i, key = 0, []
    while i < len(line):
        c = line[i]
        if c == "\\" and i + 1 < len(line):
            key.append(line[i:i + 2])
            i += 2
            continue
        if c in "=:":
            break
        key.append(c)
        i += 1
    return _unescape("".join(key).strip()), _unescape(line[i + 1:].lstrip() if i < len(line) else "")


def write_properties(text: str, wanted: dict) -> str:
    """`text` with each wanted key set, every other line (secrets, comments) untouched.

    Written the way Minecraft writes it, ASCII with \\uXXXX escapes, so it reads
    back the same whatever charset the server opens it with. Verified by parsing
    the result: raises ValueError rather than ever writing something unverified.
    """
    lines, done = text.splitlines(), set()
    for i, line in enumerate(lines):
        kv = _split(line)
        if kv and kv[0] in wanted:
            lines[i] = f"{kv[0]}={_escape(wanted[kv[0]])}"
            done.add(kv[0])
    lines += [f"{k}={_escape(v)}" for k, v in sorted(wanted.items()) if k not in done]
    out = "\n".join(lines) + "\n"
    if parse_properties(out) != {**parse_properties(text), **wanted}:
        raise ValueError("server.properties did not read back as written; nothing was saved")
    return out


def _escape(v: str) -> str:
    out = []
    for c in v:
        if c in "\\:=":
            out.append("\\" + c)
        elif " " <= c <= "~":
            out.append(c)
        else:  # Java escapes UTF-16 code units: a character outside the BMP is two
            u = c.encode("utf-16-be")
            out += [f"\\u{u[j]:02X}{u[j + 1]:02X}" for j in range(0, len(u), 2)]
    s = "".join(out)
    return "\\" + s if s.startswith(" ") else s


def _unescape(s: str) -> str:
    res, i = [], 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            n = s[i + 1]
            if n == "u" and len(s) >= i + 6:
                try:
                    res.append(chr(int(s[i + 2:i + 6], 16)))
                    i += 6
                    continue
                except ValueError:
                    pass
            res.append({"t": "\t", "n": "\n", "r": "\r", "f": "\f"}.get(n, n))
            i += 2
            continue
        res.append(c)
        i += 1
    # Rejoin 🎮-style surrogate pairs into the one character they encode.
    return "".join(res).encode("utf-16", "surrogatepass").decode("utf-16", "surrogatepass")
